# Generated by Django 3.0.5 on 2021-03-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner.Owner'),
        ),
    ]
