# Generated by Django 3.0.5 on 2021-03-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210329_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
